FROM node:18-alpine

# Instalar Mockoon CLI
RUN npm install -g @mockoon/cli

# Copiar el archivo de configuración de Mockoon
COPY percentage.json /app/percentage.json

# Exponer el puerto que usa Mockoon
EXPOSE 3001

# Comando para iniciar Mockoon en modo servidor
CMD ["mockoon-cli", "start", "--data", "/app/percentage.json", "--port", "3001"]
