version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_api
    ports:
      - "8085:8085"
    depends_on:
      - postgres
      - redis
      - mockoon
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/challenge
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      EXTERNAL_SERVICE_URL: http://mockoon:3001/api/v1/percentage
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: db_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:7
    container_name: cache_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

  mockoon:
    build:
      context: .
      dockerfile: Dockerfile.mockoon
    container_name: mockoon_service
    ports:
      - "3001:3001"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
